/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsWoocommerceRouteImport } from './routes/integrations.woocommerce'
import { Route as IInvoiceIdRouteImport } from './routes/i.$invoiceId'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated.stores'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedStoresNewRouteImport } from './routes/_authenticated.stores.new'
import { Route as AuthenticatedStoresStoreIdRouteImport } from './routes/_authenticated.stores.$storeId'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicCronWatcherRouteImport } from './routes/api/public/cron/watcher'
import { Route as ApiPublicCronRatesRouteImport } from './routes/api/public/cron/rates'
import { Route as ApiPublicCronBillingRouteImport } from './routes/api/public/cron/billing'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsWoocommerceRoute = IntegrationsWoocommerceRouteImport.update({
  id: '/integrations/woocommerce',
  path: '/integrations/woocommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const IInvoiceIdRoute = IInvoiceIdRouteImport.update({
  id: '/i/$invoiceId',
  path: '/i/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoresNewRoute = AuthenticatedStoresNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedStoresRoute,
} as any)
const AuthenticatedStoresStoreIdRoute =
  AuthenticatedStoresStoreIdRouteImport.update({
    id: '/$storeId',
    path: '/$storeId',
    getParentRoute: () => AuthenticatedStoresRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWatcherRoute = ApiPublicCronWatcherRouteImport.update({
  id: '/api/public/cron/watcher',
  path: '/api/public/cron/watcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRatesRoute = ApiPublicCronRatesRouteImport.update({
  id: '/api/public/cron/rates',
  path: '/api/public/cron/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronBillingRoute = ApiPublicCronBillingRouteImport.update({
  id: '/api/public/cron/billing',
  path: '/api/public/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/stores': typeof AuthenticatedStoresRouteWithChildren
  '/i/$invoiceId': typeof IInvoiceIdRoute
  '/integrations/woocommerce': typeof IntegrationsWoocommerceRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/stores/new': typeof AuthenticatedStoresNewRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/cron/rates': typeof ApiPublicCronRatesRoute
  '/api/public/cron/watcher': typeof ApiPublicCronWatcherRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/stores': typeof AuthenticatedStoresRouteWithChildren
  '/i/$invoiceId': typeof IInvoiceIdRoute
  '/integrations/woocommerce': typeof IntegrationsWoocommerceRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/stores/new': typeof AuthenticatedStoresNewRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/cron/rates': typeof ApiPublicCronRatesRoute
  '/api/public/cron/watcher': typeof ApiPublicCronWatcherRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRouteWithChildren
  '/i/$invoiceId': typeof IInvoiceIdRoute
  '/integrations/woocommerce': typeof IntegrationsWoocommerceRoute
  '/_authenticated/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/_authenticated/stores/new': typeof AuthenticatedStoresNewRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/cron/rates': typeof ApiPublicCronRatesRoute
  '/api/public/cron/watcher': typeof ApiPublicCronWatcherRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/pricing'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/stores'
    | '/i/$invoiceId'
    | '/integrations/woocommerce'
    | '/stores/$storeId'
    | '/stores/new'
    | '/api/public/cron/billing'
    | '/api/public/cron/rates'
    | '/api/public/cron/watcher'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/pricing'
    | '/billing'
    | '/dashboard'
    | '/notifications'
    | '/stores'
    | '/i/$invoiceId'
    | '/integrations/woocommerce'
    | '/stores/$storeId'
    | '/stores/new'
    | '/api/public/cron/billing'
    | '/api/public/cron/rates'
    | '/api/public/cron/watcher'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/pricing'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/stores'
    | '/i/$invoiceId'
    | '/integrations/woocommerce'
    | '/_authenticated/stores/$storeId'
    | '/_authenticated/stores/new'
    | '/api/public/cron/billing'
    | '/api/public/cron/rates'
    | '/api/public/cron/watcher'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  IInvoiceIdRoute: typeof IInvoiceIdRoute
  IntegrationsWoocommerceRoute: typeof IntegrationsWoocommerceRoute
  ApiPublicCronBillingRoute: typeof ApiPublicCronBillingRoute
  ApiPublicCronRatesRoute: typeof ApiPublicCronRatesRoute
  ApiPublicCronWatcherRoute: typeof ApiPublicCronWatcherRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/woocommerce': {
      id: '/integrations/woocommerce'
      path: '/integrations/woocommerce'
      fullPath: '/integrations/woocommerce'
      preLoaderRoute: typeof IntegrationsWoocommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$invoiceId': {
      id: '/i/$invoiceId'
      path: '/i/$invoiceId'
      fullPath: '/i/$invoiceId'
      preLoaderRoute: typeof IInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stores/new': {
      id: '/_authenticated/stores/new'
      path: '/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof AuthenticatedStoresNewRouteImport
      parentRoute: typeof AuthenticatedStoresRoute
    }
    '/_authenticated/stores/$storeId': {
      id: '/_authenticated/stores/$storeId'
      path: '/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedStoresRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/watcher': {
      id: '/api/public/cron/watcher'
      path: '/api/public/cron/watcher'
      fullPath: '/api/public/cron/watcher'
      preLoaderRoute: typeof ApiPublicCronWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/rates': {
      id: '/api/public/cron/rates'
      path: '/api/public/cron/rates'
      fullPath: '/api/public/cron/rates'
      preLoaderRoute: typeof ApiPublicCronRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/billing': {
      id: '/api/public/cron/billing'
      path: '/api/public/cron/billing'
      fullPath: '/api/public/cron/billing'
      preLoaderRoute: typeof ApiPublicCronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedStoresRouteChildren {
  AuthenticatedStoresStoreIdRoute: typeof AuthenticatedStoresStoreIdRoute
  AuthenticatedStoresNewRoute: typeof AuthenticatedStoresNewRoute
}

const AuthenticatedStoresRouteChildren: AuthenticatedStoresRouteChildren = {
  AuthenticatedStoresStoreIdRoute: AuthenticatedStoresStoreIdRoute,
  AuthenticatedStoresNewRoute: AuthenticatedStoresNewRoute,
}

const AuthenticatedStoresRouteWithChildren =
  AuthenticatedStoresRoute._addFileChildren(AuthenticatedStoresRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  IInvoiceIdRoute: IInvoiceIdRoute,
  IntegrationsWoocommerceRoute: IntegrationsWoocommerceRoute,
  ApiPublicCronBillingRoute: ApiPublicCronBillingRoute,
  ApiPublicCronRatesRoute: ApiPublicCronRatesRoute,
  ApiPublicCronWatcherRoute: ApiPublicCronWatcherRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
