/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhereRouteImport } from './routes/where'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PriceRouteImport } from './routes/price'
import { Route as PosBuildIdRouteImport } from './routes/pos-build-id'
import { Route as PosApkRouteImport } from './routes/pos-apk'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OnrampRouteImport } from './routes/onramp'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as MRouteImport } from './routes/m'
import { Route as LiveRouteImport } from './routes/live'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as IntegrateRouteImport } from './routes/integrate'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CashOutRouteImport } from './routes/cash-out'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as SdkPayhmeDotjsRouteImport } from './routes/sdk.payhme[.]js'
import { Route as PosSettingsRouteImport } from './routes/pos.settings'
import { Route as PosPrinterTestRouteImport } from './routes/pos.printer-test'
import { Route as PosPairSigninRouteImport } from './routes/pos.pair-signin'
import { Route as PosPairRouteImport } from './routes/pos.pair'
import { Route as PosNfcInspectRouteImport } from './routes/pos.nfc-inspect'
import { Route as PosHistoryRouteImport } from './routes/pos.history'
import { Route as PayInvoiceIdRouteImport } from './routes/pay.$invoiceId'
import { Route as IntegrationsWoocommerceRouteImport } from './routes/integrations.woocommerce'
import { Route as IInvoiceIdRouteImport } from './routes/i.$invoiceId'
import { Route as DocsWalletSetupRouteImport } from './routes/docs.wallet-setup'
import { Route as DocsTapToPayTangemRouteImport } from './routes/docs.tap-to-pay-tangem'
import { Route as DevTangemTestRouteImport } from './routes/dev.tangem-test'
import { Route as CheckoutThanksRouteImport } from './routes/checkout.thanks'
import { Route as AuthenticatedTerminalsRouteImport } from './routes/_authenticated.terminals'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedExportsRouteImport } from './routes/_authenticated.exports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedStoresIndexRouteImport } from './routes/_authenticated.stores.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedStoresNewRouteImport } from './routes/_authenticated.stores.new'
import { Route as AuthenticatedStoresStoreIdRouteImport } from './routes/_authenticated.stores.$storeId'
import { Route as AuthenticatedMVirtualTerminalRouteImport } from './routes/_authenticated.m.virtual-terminal'
import { Route as AuthenticatedMHomeRouteImport } from './routes/_authenticated.m.home'
import { Route as AuthenticatedAdminMerchantsRouteImport } from './routes/_authenticated.admin.merchants'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated.admin.leads'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated.admin.knowledge'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated.admin.invoices'
import { Route as AuthenticatedStoresStoreIdIndexRouteImport } from './routes/_authenticated.stores.$storeId.index'
import { Route as AuthenticatedAdminKnowledgeIndexRouteImport } from './routes/_authenticated.admin.knowledge.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicV1WalletLinkRouteImport } from './routes/api/public/v1/wallet-link'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1/me'
import { Route as ApiPublicV1InvoicesRouteImport } from './routes/api.public.v1.invoices'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksAlchemyActivityRouteImport } from './routes/api/public/hooks/alchemy-activity'
import { Route as ApiPublicCronWatcherRouteImport } from './routes/api/public/cron/watcher'
import { Route as ApiPublicCronRatesRouteImport } from './routes/api/public/cron/rates'
import { Route as ApiPublicCronBillingRouteImport } from './routes/api/public/cron/billing'
import { Route as ApiPublicCronAlchemySyncRouteImport } from './routes/api/public/cron/alchemy-sync'
import { Route as ApiPublicAuthWalletStatusRouteImport } from './routes/api/public/auth/wallet-status'
import { Route as ApiPublicAuthWalletExchangeRouteImport } from './routes/api/public/auth/wallet-exchange'
import { Route as ApiPublicAuthWalletChallengeRouteImport } from './routes/api/public/auth/wallet-challenge'
import { Route as ApiPublicAuthWalletCallbackRouteImport } from './routes/api/public/auth/wallet-callback'
import { Route as AuthenticatedStoresStoreIdTerminalsRouteImport } from './routes/_authenticated.stores.$storeId.terminals'
import { Route as AuthenticatedStoresStoreIdTangemRouteImport } from './routes/_authenticated.stores.$storeId.tangem'
import { Route as AuthenticatedStoresStoreIdPosSettingsRouteImport } from './routes/_authenticated.stores.$storeId.pos-settings'
import { Route as AuthenticatedStoresStoreIdListingRouteImport } from './routes/_authenticated.stores.$storeId.listing'
import { Route as AuthenticatedStoresStoreIdKycRouteImport } from './routes/_authenticated.stores.$storeId.kyc'
import { Route as AuthenticatedStoresStoreIdKeysRouteImport } from './routes/_authenticated.stores.$storeId.keys'
import { Route as AuthenticatedStoresStoreIdChainsRouteImport } from './routes/_authenticated.stores.$storeId.chains'
import { Route as AuthenticatedAdminKnowledgeTermsRouteImport } from './routes/_authenticated.admin.knowledge.terms'
import { Route as AuthenticatedAdminKnowledgePrivacyRouteImport } from './routes/_authenticated.admin.knowledge.privacy'
import { Route as AuthenticatedAdminKnowledgeMembersHeatmapRouteImport } from './routes/_authenticated.admin.knowledge.members-heatmap'
import { Route as AuthenticatedAdminKnowledgeManifestoRouteImport } from './routes/_authenticated.admin.knowledge.manifesto'
import { Route as AuthenticatedAdminKnowledgeExecutiveSummaryRouteImport } from './routes/_authenticated.admin.knowledge.executive-summary'
import { Route as AuthenticatedAdminKnowledgeConvenienceDoctrineRouteImport } from './routes/_authenticated.admin.knowledge.convenience-doctrine'
import { Route as ApiPublicV1TerminalsPairRouteImport } from './routes/api/public/v1/terminals/pair'
import { Route as ApiPublicV1TerminalsOptionsRouteImport } from './routes/api/public/v1/terminals/options'
import { Route as ApiPublicV1TerminalsInvoiceRouteImport } from './routes/api/public/v1/terminals/invoice'
import { Route as ApiPublicV1TerminalsHeartbeatRouteImport } from './routes/api/public/v1/terminals/heartbeat'
import { Route as ApiPublicV1PayInvoiceIdRouteImport } from './routes/api/public/v1/pay/$invoiceId'
import { Route as ApiPublicV1InvoicesIdRouteImport } from './routes/api.public.v1.invoices.$id'
import { Route as AuthenticatedAdminKnowledgeTrainingSalesRepsRouteImport } from './routes/_authenticated.admin.knowledge.training.sales-reps'
import { Route as AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRouteImport } from './routes/_authenticated.admin.knowledge.training.merchant-onboarding'
import { Route as AuthenticatedAdminKnowledgeTrainingCryptopopRouteImport } from './routes/_authenticated.admin.knowledge.training.cryptopop'
import { Route as AuthenticatedAdminKnowledgePitchNewMarketsRouteImport } from './routes/_authenticated.admin.knowledge.pitch.new-markets'
import { Route as AuthenticatedAdminKnowledgePitchMerchantsRouteImport } from './routes/_authenticated.admin.knowledge.pitch.merchants'
import { Route as AuthenticatedAdminKnowledgePitchConsumersRouteImport } from './routes/_authenticated.admin.knowledge.pitch.consumers'
import { Route as ApiPublicV1TerminalsInvoiceIdRouteImport } from './routes/api/public/v1/terminals/invoice.$id'
import { Route as ApiPublicV1TerminalsInvoiceIdReceiptRouteImport } from './routes/api/public/v1/terminals/invoice.$id.receipt'
import { Route as ApiPublicV1TerminalsInvoiceIdCancelRouteImport } from './routes/api/public/v1/terminals/invoice.$id.cancel'

const WhereRoute = WhereRouteImport.update({
  id: '/where',
  path: '/where',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceRoute = PriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => rootRouteImport,
} as any)
const PosBuildIdRoute = PosBuildIdRouteImport.update({
  id: '/pos-build-id',
  path: '/pos-build-id',
  getParentRoute: () => rootRouteImport,
} as any)
const PosApkRoute = PosApkRouteImport.update({
  id: '/pos-apk',
  path: '/pos-apk',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnrampRoute = OnrampRouteImport.update({
  id: '/onramp',
  path: '/onramp',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrateRoute = IntegrateRouteImport.update({
  id: '/integrate',
  path: '/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CashOutRoute = CashOutRouteImport.update({
  id: '/cash-out',
  path: '/cash-out',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkPayhmeDotjsRoute = SdkPayhmeDotjsRouteImport.update({
  id: '/sdk/payhme.js',
  path: '/sdk/payhme.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSettingsRoute = PosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosRoute,
} as any)
const PosPrinterTestRoute = PosPrinterTestRouteImport.update({
  id: '/printer-test',
  path: '/printer-test',
  getParentRoute: () => PosRoute,
} as any)
const PosPairSigninRoute = PosPairSigninRouteImport.update({
  id: '/pair-signin',
  path: '/pair-signin',
  getParentRoute: () => PosRoute,
} as any)
const PosPairRoute = PosPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => PosRoute,
} as any)
const PosNfcInspectRoute = PosNfcInspectRouteImport.update({
  id: '/nfc-inspect',
  path: '/nfc-inspect',
  getParentRoute: () => PosRoute,
} as any)
const PosHistoryRoute = PosHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PosRoute,
} as any)
const PayInvoiceIdRoute = PayInvoiceIdRouteImport.update({
  id: '/pay/$invoiceId',
  path: '/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsWoocommerceRoute = IntegrationsWoocommerceRouteImport.update({
  id: '/integrations/woocommerce',
  path: '/integrations/woocommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const IInvoiceIdRoute = IInvoiceIdRouteImport.update({
  id: '/i/$invoiceId',
  path: '/i/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWalletSetupRoute = DocsWalletSetupRouteImport.update({
  id: '/wallet-setup',
  path: '/wallet-setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTapToPayTangemRoute = DocsTapToPayTangemRouteImport.update({
  id: '/tap-to-pay-tangem',
  path: '/tap-to-pay-tangem',
  getParentRoute: () => DocsRoute,
} as any)
const DevTangemTestRoute = DevTangemTestRouteImport.update({
  id: '/dev/tangem-test',
  path: '/dev/tangem-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutThanksRoute = CheckoutThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedTerminalsRoute = AuthenticatedTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoresIndexRoute =
  AuthenticatedStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStoresNewRoute = AuthenticatedStoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoresStoreIdRoute =
  AuthenticatedStoresStoreIdRouteImport.update({
    id: '/stores/$storeId',
    path: '/stores/$storeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMVirtualTerminalRoute =
  AuthenticatedMVirtualTerminalRouteImport.update({
    id: '/m/virtual-terminal',
    path: '/m/virtual-terminal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMHomeRoute = AuthenticatedMHomeRouteImport.update({
  id: '/m/home',
  path: '/m/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMerchantsRoute =
  AuthenticatedAdminMerchantsRouteImport.update({
    id: '/merchants',
    path: '/merchants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStoresStoreIdIndexRoute =
  AuthenticatedStoresStoreIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedAdminKnowledgeIndexRoute =
  AuthenticatedAdminKnowledgeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1WalletLinkRoute = ApiPublicV1WalletLinkRouteImport.update({
  id: '/api/public/v1/wallet-link',
  path: '/api/public/v1/wallet-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InvoicesRoute = ApiPublicV1InvoicesRouteImport.update({
  id: '/api/public/v1/invoices',
  path: '/api/public/v1/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAlchemyActivityRoute =
  ApiPublicHooksAlchemyActivityRouteImport.update({
    id: '/api/public/hooks/alchemy-activity',
    path: '/api/public/hooks/alchemy-activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronWatcherRoute = ApiPublicCronWatcherRouteImport.update({
  id: '/api/public/cron/watcher',
  path: '/api/public/cron/watcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRatesRoute = ApiPublicCronRatesRouteImport.update({
  id: '/api/public/cron/rates',
  path: '/api/public/cron/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronBillingRoute = ApiPublicCronBillingRouteImport.update({
  id: '/api/public/cron/billing',
  path: '/api/public/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAlchemySyncRoute =
  ApiPublicCronAlchemySyncRouteImport.update({
    id: '/api/public/cron/alchemy-sync',
    path: '/api/public/cron/alchemy-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletStatusRoute =
  ApiPublicAuthWalletStatusRouteImport.update({
    id: '/api/public/auth/wallet-status',
    path: '/api/public/auth/wallet-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletExchangeRoute =
  ApiPublicAuthWalletExchangeRouteImport.update({
    id: '/api/public/auth/wallet-exchange',
    path: '/api/public/auth/wallet-exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletChallengeRoute =
  ApiPublicAuthWalletChallengeRouteImport.update({
    id: '/api/public/auth/wallet-challenge',
    path: '/api/public/auth/wallet-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletCallbackRoute =
  ApiPublicAuthWalletCallbackRouteImport.update({
    id: '/api/public/auth/wallet-callback',
    path: '/api/public/auth/wallet-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStoresStoreIdTerminalsRoute =
  AuthenticatedStoresStoreIdTerminalsRouteImport.update({
    id: '/terminals',
    path: '/terminals',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdTangemRoute =
  AuthenticatedStoresStoreIdTangemRouteImport.update({
    id: '/tangem',
    path: '/tangem',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdPosSettingsRoute =
  AuthenticatedStoresStoreIdPosSettingsRouteImport.update({
    id: '/pos-settings',
    path: '/pos-settings',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdListingRoute =
  AuthenticatedStoresStoreIdListingRouteImport.update({
    id: '/listing',
    path: '/listing',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdKycRoute =
  AuthenticatedStoresStoreIdKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdKeysRoute =
  AuthenticatedStoresStoreIdKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdChainsRoute =
  AuthenticatedStoresStoreIdChainsRouteImport.update({
    id: '/chains',
    path: '/chains',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedAdminKnowledgeTermsRoute =
  AuthenticatedAdminKnowledgeTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePrivacyRoute =
  AuthenticatedAdminKnowledgePrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeMembersHeatmapRoute =
  AuthenticatedAdminKnowledgeMembersHeatmapRouteImport.update({
    id: '/members-heatmap',
    path: '/members-heatmap',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeManifestoRoute =
  AuthenticatedAdminKnowledgeManifestoRouteImport.update({
    id: '/manifesto',
    path: '/manifesto',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeExecutiveSummaryRoute =
  AuthenticatedAdminKnowledgeExecutiveSummaryRouteImport.update({
    id: '/executive-summary',
    path: '/executive-summary',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeConvenienceDoctrineRoute =
  AuthenticatedAdminKnowledgeConvenienceDoctrineRouteImport.update({
    id: '/convenience-doctrine',
    path: '/convenience-doctrine',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const ApiPublicV1TerminalsPairRoute =
  ApiPublicV1TerminalsPairRouteImport.update({
    id: '/api/public/v1/terminals/pair',
    path: '/api/public/v1/terminals/pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TerminalsOptionsRoute =
  ApiPublicV1TerminalsOptionsRouteImport.update({
    id: '/api/public/v1/terminals/options',
    path: '/api/public/v1/terminals/options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TerminalsInvoiceRoute =
  ApiPublicV1TerminalsInvoiceRouteImport.update({
    id: '/api/public/v1/terminals/invoice',
    path: '/api/public/v1/terminals/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TerminalsHeartbeatRoute =
  ApiPublicV1TerminalsHeartbeatRouteImport.update({
    id: '/api/public/v1/terminals/heartbeat',
    path: '/api/public/v1/terminals/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1PayInvoiceIdRoute = ApiPublicV1PayInvoiceIdRouteImport.update({
  id: '/api/public/v1/pay/$invoiceId',
  path: '/api/public/v1/pay/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InvoicesIdRoute = ApiPublicV1InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1InvoicesRoute,
} as any)
const AuthenticatedAdminKnowledgeTrainingSalesRepsRoute =
  AuthenticatedAdminKnowledgeTrainingSalesRepsRouteImport.update({
    id: '/training/sales-reps',
    path: '/training/sales-reps',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute =
  AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRouteImport.update({
    id: '/training/merchant-onboarding',
    path: '/training/merchant-onboarding',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeTrainingCryptopopRoute =
  AuthenticatedAdminKnowledgeTrainingCryptopopRouteImport.update({
    id: '/training/cryptopop',
    path: '/training/cryptopop',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePitchNewMarketsRoute =
  AuthenticatedAdminKnowledgePitchNewMarketsRouteImport.update({
    id: '/pitch/new-markets',
    path: '/pitch/new-markets',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePitchMerchantsRoute =
  AuthenticatedAdminKnowledgePitchMerchantsRouteImport.update({
    id: '/pitch/merchants',
    path: '/pitch/merchants',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePitchConsumersRoute =
  AuthenticatedAdminKnowledgePitchConsumersRouteImport.update({
    id: '/pitch/consumers',
    path: '/pitch/consumers',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const ApiPublicV1TerminalsInvoiceIdRoute =
  ApiPublicV1TerminalsInvoiceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicV1TerminalsInvoiceRoute,
  } as any)
const ApiPublicV1TerminalsInvoiceIdReceiptRoute =
  ApiPublicV1TerminalsInvoiceIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => ApiPublicV1TerminalsInvoiceIdRoute,
  } as any)
const ApiPublicV1TerminalsInvoiceIdCancelRoute =
  ApiPublicV1TerminalsInvoiceIdCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => ApiPublicV1TerminalsInvoiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/cash-out': typeof CashOutRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/integrate': typeof IntegrateRoute
  '/investors': typeof InvestorsRoute
  '/live': typeof LiveRoute
  '/m': typeof MRoute
  '/manifesto': typeof ManifestoRoute
  '/onramp': typeof OnrampRoute
  '/pos': typeof PosRouteWithChildren
  '/pos-apk': typeof PosApkRoute
  '/pos-build-id': typeof PosBuildIdRoute
  '/price': typeof PriceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/where': typeof WhereRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/terminals': typeof AuthenticatedTerminalsRoute
  '/checkout/thanks': typeof CheckoutThanksRoute
  '/dev/tangem-test': typeof DevTangemTestRoute
  '/docs/tap-to-pay-tangem': typeof DocsTapToPayTangemRoute
  '/docs/wallet-setup': typeof DocsWalletSetupRoute
  '/i/$invoiceId': typeof IInvoiceIdRoute
  '/integrations/woocommerce': typeof IntegrationsWoocommerceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/nfc-inspect': typeof PosNfcInspectRoute
  '/pos/pair': typeof PosPairRoute
  '/pos/pair-signin': typeof PosPairSigninRoute
  '/pos/printer-test': typeof PosPrinterTestRoute
  '/pos/settings': typeof PosSettingsRoute
  '/sdk/payhme.js': typeof SdkPayhmeDotjsRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/pos/': typeof PosIndexRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRouteWithChildren
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/m/home': typeof AuthenticatedMHomeRoute
  '/m/virtual-terminal': typeof AuthenticatedMVirtualTerminalRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRouteWithChildren
  '/stores/new': typeof AuthenticatedStoresNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/stores/': typeof AuthenticatedStoresIndexRoute
  '/admin/knowledge/convenience-doctrine': typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  '/admin/knowledge/executive-summary': typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  '/admin/knowledge/manifesto': typeof AuthenticatedAdminKnowledgeManifestoRoute
  '/admin/knowledge/members-heatmap': typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  '/admin/knowledge/privacy': typeof AuthenticatedAdminKnowledgePrivacyRoute
  '/admin/knowledge/terms': typeof AuthenticatedAdminKnowledgeTermsRoute
  '/stores/$storeId/chains': typeof AuthenticatedStoresStoreIdChainsRoute
  '/stores/$storeId/keys': typeof AuthenticatedStoresStoreIdKeysRoute
  '/stores/$storeId/kyc': typeof AuthenticatedStoresStoreIdKycRoute
  '/stores/$storeId/listing': typeof AuthenticatedStoresStoreIdListingRoute
  '/stores/$storeId/pos-settings': typeof AuthenticatedStoresStoreIdPosSettingsRoute
  '/stores/$storeId/tangem': typeof AuthenticatedStoresStoreIdTangemRoute
  '/stores/$storeId/terminals': typeof AuthenticatedStoresStoreIdTerminalsRoute
  '/api/public/auth/wallet-callback': typeof ApiPublicAuthWalletCallbackRoute
  '/api/public/auth/wallet-challenge': typeof ApiPublicAuthWalletChallengeRoute
  '/api/public/auth/wallet-exchange': typeof ApiPublicAuthWalletExchangeRoute
  '/api/public/auth/wallet-status': typeof ApiPublicAuthWalletStatusRoute
  '/api/public/cron/alchemy-sync': typeof ApiPublicCronAlchemySyncRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/cron/rates': typeof ApiPublicCronRatesRoute
  '/api/public/cron/watcher': typeof ApiPublicCronWatcherRoute
  '/api/public/hooks/alchemy-activity': typeof ApiPublicHooksAlchemyActivityRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRouteWithChildren
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/wallet-link': typeof ApiPublicV1WalletLinkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/stores/$storeId/': typeof AuthenticatedStoresStoreIdIndexRoute
  '/admin/knowledge/pitch/consumers': typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  '/admin/knowledge/pitch/merchants': typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  '/admin/knowledge/pitch/new-markets': typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  '/admin/knowledge/training/cryptopop': typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  '/admin/knowledge/training/merchant-onboarding': typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  '/admin/knowledge/training/sales-reps': typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
  '/api/public/v1/invoices/$id': typeof ApiPublicV1InvoicesIdRoute
  '/api/public/v1/pay/$invoiceId': typeof ApiPublicV1PayInvoiceIdRoute
  '/api/public/v1/terminals/heartbeat': typeof ApiPublicV1TerminalsHeartbeatRoute
  '/api/public/v1/terminals/invoice': typeof ApiPublicV1TerminalsInvoiceRouteWithChildren
  '/api/public/v1/terminals/options': typeof ApiPublicV1TerminalsOptionsRoute
  '/api/public/v1/terminals/pair': typeof ApiPublicV1TerminalsPairRoute
  '/api/public/v1/terminals/invoice/$id': typeof ApiPublicV1TerminalsInvoiceIdRouteWithChildren
  '/api/public/v1/terminals/invoice/$id/cancel': typeof ApiPublicV1TerminalsInvoiceIdCancelRoute
  '/api/public/v1/terminals/invoice/$id/receipt': typeof ApiPublicV1TerminalsInvoiceIdReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/cash-out': typeof CashOutRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/integrate': typeof IntegrateRoute
  '/investors': typeof InvestorsRoute
  '/live': typeof LiveRoute
  '/m': typeof MRoute
  '/manifesto': typeof ManifestoRoute
  '/onramp': typeof OnrampRoute
  '/pos-apk': typeof PosApkRoute
  '/pos-build-id': typeof PosBuildIdRoute
  '/price': typeof PriceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/where': typeof WhereRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/terminals': typeof AuthenticatedTerminalsRoute
  '/checkout/thanks': typeof CheckoutThanksRoute
  '/dev/tangem-test': typeof DevTangemTestRoute
  '/docs/tap-to-pay-tangem': typeof DocsTapToPayTangemRoute
  '/docs/wallet-setup': typeof DocsWalletSetupRoute
  '/i/$invoiceId': typeof IInvoiceIdRoute
  '/integrations/woocommerce': typeof IntegrationsWoocommerceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/nfc-inspect': typeof PosNfcInspectRoute
  '/pos/pair': typeof PosPairRoute
  '/pos/pair-signin': typeof PosPairSigninRoute
  '/pos/printer-test': typeof PosPrinterTestRoute
  '/pos/settings': typeof PosSettingsRoute
  '/sdk/payhme.js': typeof SdkPayhmeDotjsRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/pos': typeof PosIndexRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/m/home': typeof AuthenticatedMHomeRoute
  '/m/virtual-terminal': typeof AuthenticatedMVirtualTerminalRoute
  '/stores/new': typeof AuthenticatedStoresNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
  '/admin/knowledge/convenience-doctrine': typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  '/admin/knowledge/executive-summary': typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  '/admin/knowledge/manifesto': typeof AuthenticatedAdminKnowledgeManifestoRoute
  '/admin/knowledge/members-heatmap': typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  '/admin/knowledge/privacy': typeof AuthenticatedAdminKnowledgePrivacyRoute
  '/admin/knowledge/terms': typeof AuthenticatedAdminKnowledgeTermsRoute
  '/stores/$storeId/chains': typeof AuthenticatedStoresStoreIdChainsRoute
  '/stores/$storeId/keys': typeof AuthenticatedStoresStoreIdKeysRoute
  '/stores/$storeId/kyc': typeof AuthenticatedStoresStoreIdKycRoute
  '/stores/$storeId/listing': typeof AuthenticatedStoresStoreIdListingRoute
  '/stores/$storeId/pos-settings': typeof AuthenticatedStoresStoreIdPosSettingsRoute
  '/stores/$storeId/tangem': typeof AuthenticatedStoresStoreIdTangemRoute
  '/stores/$storeId/terminals': typeof AuthenticatedStoresStoreIdTerminalsRoute
  '/api/public/auth/wallet-callback': typeof ApiPublicAuthWalletCallbackRoute
  '/api/public/auth/wallet-challenge': typeof ApiPublicAuthWalletChallengeRoute
  '/api/public/auth/wallet-exchange': typeof ApiPublicAuthWalletExchangeRoute
  '/api/public/auth/wallet-status': typeof ApiPublicAuthWalletStatusRoute
  '/api/public/cron/alchemy-sync': typeof ApiPublicCronAlchemySyncRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/cron/rates': typeof ApiPublicCronRatesRoute
  '/api/public/cron/watcher': typeof ApiPublicCronWatcherRoute
  '/api/public/hooks/alchemy-activity': typeof ApiPublicHooksAlchemyActivityRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRouteWithChildren
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/wallet-link': typeof ApiPublicV1WalletLinkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdIndexRoute
  '/admin/knowledge/pitch/consumers': typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  '/admin/knowledge/pitch/merchants': typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  '/admin/knowledge/pitch/new-markets': typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  '/admin/knowledge/training/cryptopop': typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  '/admin/knowledge/training/merchant-onboarding': typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  '/admin/knowledge/training/sales-reps': typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
  '/api/public/v1/invoices/$id': typeof ApiPublicV1InvoicesIdRoute
  '/api/public/v1/pay/$invoiceId': typeof ApiPublicV1PayInvoiceIdRoute
  '/api/public/v1/terminals/heartbeat': typeof ApiPublicV1TerminalsHeartbeatRoute
  '/api/public/v1/terminals/invoice': typeof ApiPublicV1TerminalsInvoiceRouteWithChildren
  '/api/public/v1/terminals/options': typeof ApiPublicV1TerminalsOptionsRoute
  '/api/public/v1/terminals/pair': typeof ApiPublicV1TerminalsPairRoute
  '/api/public/v1/terminals/invoice/$id': typeof ApiPublicV1TerminalsInvoiceIdRouteWithChildren
  '/api/public/v1/terminals/invoice/$id/cancel': typeof ApiPublicV1TerminalsInvoiceIdCancelRoute
  '/api/public/v1/terminals/invoice/$id/receipt': typeof ApiPublicV1TerminalsInvoiceIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/cash-out': typeof CashOutRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/integrate': typeof IntegrateRoute
  '/investors': typeof InvestorsRoute
  '/live': typeof LiveRoute
  '/m': typeof MRoute
  '/manifesto': typeof ManifestoRoute
  '/onramp': typeof OnrampRoute
  '/pos': typeof PosRouteWithChildren
  '/pos-apk': typeof PosApkRoute
  '/pos-build-id': typeof PosBuildIdRoute
  '/price': typeof PriceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/where': typeof WhereRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exports': typeof AuthenticatedExportsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/terminals': typeof AuthenticatedTerminalsRoute
  '/checkout/thanks': typeof CheckoutThanksRoute
  '/dev/tangem-test': typeof DevTangemTestRoute
  '/docs/tap-to-pay-tangem': typeof DocsTapToPayTangemRoute
  '/docs/wallet-setup': typeof DocsWalletSetupRoute
  '/i/$invoiceId': typeof IInvoiceIdRoute
  '/integrations/woocommerce': typeof IntegrationsWoocommerceRoute
  '/pay/$invoiceId': typeof PayInvoiceIdRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/nfc-inspect': typeof PosNfcInspectRoute
  '/pos/pair': typeof PosPairRoute
  '/pos/pair-signin': typeof PosPairSigninRoute
  '/pos/printer-test': typeof PosPrinterTestRoute
  '/pos/settings': typeof PosSettingsRoute
  '/sdk/payhme.js': typeof SdkPayhmeDotjsRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/pos/': typeof PosIndexRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRouteWithChildren
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/_authenticated/m/home': typeof AuthenticatedMHomeRoute
  '/_authenticated/m/virtual-terminal': typeof AuthenticatedMVirtualTerminalRoute
  '/_authenticated/stores/$storeId': typeof AuthenticatedStoresStoreIdRouteWithChildren
  '/_authenticated/stores/new': typeof AuthenticatedStoresNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/stores/': typeof AuthenticatedStoresIndexRoute
  '/_authenticated/admin/knowledge/convenience-doctrine': typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  '/_authenticated/admin/knowledge/executive-summary': typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  '/_authenticated/admin/knowledge/manifesto': typeof AuthenticatedAdminKnowledgeManifestoRoute
  '/_authenticated/admin/knowledge/members-heatmap': typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  '/_authenticated/admin/knowledge/privacy': typeof AuthenticatedAdminKnowledgePrivacyRoute
  '/_authenticated/admin/knowledge/terms': typeof AuthenticatedAdminKnowledgeTermsRoute
  '/_authenticated/stores/$storeId/chains': typeof AuthenticatedStoresStoreIdChainsRoute
  '/_authenticated/stores/$storeId/keys': typeof AuthenticatedStoresStoreIdKeysRoute
  '/_authenticated/stores/$storeId/kyc': typeof AuthenticatedStoresStoreIdKycRoute
  '/_authenticated/stores/$storeId/listing': typeof AuthenticatedStoresStoreIdListingRoute
  '/_authenticated/stores/$storeId/pos-settings': typeof AuthenticatedStoresStoreIdPosSettingsRoute
  '/_authenticated/stores/$storeId/tangem': typeof AuthenticatedStoresStoreIdTangemRoute
  '/_authenticated/stores/$storeId/terminals': typeof AuthenticatedStoresStoreIdTerminalsRoute
  '/api/public/auth/wallet-callback': typeof ApiPublicAuthWalletCallbackRoute
  '/api/public/auth/wallet-challenge': typeof ApiPublicAuthWalletChallengeRoute
  '/api/public/auth/wallet-exchange': typeof ApiPublicAuthWalletExchangeRoute
  '/api/public/auth/wallet-status': typeof ApiPublicAuthWalletStatusRoute
  '/api/public/cron/alchemy-sync': typeof ApiPublicCronAlchemySyncRoute
  '/api/public/cron/billing': typeof ApiPublicCronBillingRoute
  '/api/public/cron/rates': typeof ApiPublicCronRatesRoute
  '/api/public/cron/watcher': typeof ApiPublicCronWatcherRoute
  '/api/public/hooks/alchemy-activity': typeof ApiPublicHooksAlchemyActivityRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRouteWithChildren
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/wallet-link': typeof ApiPublicV1WalletLinkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/_authenticated/stores/$storeId/': typeof AuthenticatedStoresStoreIdIndexRoute
  '/_authenticated/admin/knowledge/pitch/consumers': typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  '/_authenticated/admin/knowledge/pitch/merchants': typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  '/_authenticated/admin/knowledge/pitch/new-markets': typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  '/_authenticated/admin/knowledge/training/cryptopop': typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  '/_authenticated/admin/knowledge/training/merchant-onboarding': typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  '/_authenticated/admin/knowledge/training/sales-reps': typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
  '/api/public/v1/invoices/$id': typeof ApiPublicV1InvoicesIdRoute
  '/api/public/v1/pay/$invoiceId': typeof ApiPublicV1PayInvoiceIdRoute
  '/api/public/v1/terminals/heartbeat': typeof ApiPublicV1TerminalsHeartbeatRoute
  '/api/public/v1/terminals/invoice': typeof ApiPublicV1TerminalsInvoiceRouteWithChildren
  '/api/public/v1/terminals/options': typeof ApiPublicV1TerminalsOptionsRoute
  '/api/public/v1/terminals/pair': typeof ApiPublicV1TerminalsPairRoute
  '/api/public/v1/terminals/invoice/$id': typeof ApiPublicV1TerminalsInvoiceIdRouteWithChildren
  '/api/public/v1/terminals/invoice/$id/cancel': typeof ApiPublicV1TerminalsInvoiceIdCancelRoute
  '/api/public/v1/terminals/invoice/$id/receipt': typeof ApiPublicV1TerminalsInvoiceIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brand'
    | '/cash-out'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/docs'
    | '/integrate'
    | '/investors'
    | '/live'
    | '/m'
    | '/manifesto'
    | '/onramp'
    | '/pos'
    | '/pos-apk'
    | '/pos-build-id'
    | '/price'
    | '/pricing'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/where'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/exports'
    | '/notifications'
    | '/terminals'
    | '/checkout/thanks'
    | '/dev/tangem-test'
    | '/docs/tap-to-pay-tangem'
    | '/docs/wallet-setup'
    | '/i/$invoiceId'
    | '/integrations/woocommerce'
    | '/pay/$invoiceId'
    | '/pos/history'
    | '/pos/nfc-inspect'
    | '/pos/pair'
    | '/pos/pair-signin'
    | '/pos/printer-test'
    | '/pos/settings'
    | '/sdk/payhme.js'
    | '/integrations/'
    | '/pos/'
    | '/admin/invoices'
    | '/admin/knowledge'
    | '/admin/leads'
    | '/admin/merchants'
    | '/m/home'
    | '/m/virtual-terminal'
    | '/stores/$storeId'
    | '/stores/new'
    | '/admin/'
    | '/stores/'
    | '/admin/knowledge/convenience-doctrine'
    | '/admin/knowledge/executive-summary'
    | '/admin/knowledge/manifesto'
    | '/admin/knowledge/members-heatmap'
    | '/admin/knowledge/privacy'
    | '/admin/knowledge/terms'
    | '/stores/$storeId/chains'
    | '/stores/$storeId/keys'
    | '/stores/$storeId/kyc'
    | '/stores/$storeId/listing'
    | '/stores/$storeId/pos-settings'
    | '/stores/$storeId/tangem'
    | '/stores/$storeId/terminals'
    | '/api/public/auth/wallet-callback'
    | '/api/public/auth/wallet-challenge'
    | '/api/public/auth/wallet-exchange'
    | '/api/public/auth/wallet-status'
    | '/api/public/cron/alchemy-sync'
    | '/api/public/cron/billing'
    | '/api/public/cron/rates'
    | '/api/public/cron/watcher'
    | '/api/public/hooks/alchemy-activity'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/invoices'
    | '/api/public/v1/me'
    | '/api/public/v1/wallet-link'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/knowledge/'
    | '/stores/$storeId/'
    | '/admin/knowledge/pitch/consumers'
    | '/admin/knowledge/pitch/merchants'
    | '/admin/knowledge/pitch/new-markets'
    | '/admin/knowledge/training/cryptopop'
    | '/admin/knowledge/training/merchant-onboarding'
    | '/admin/knowledge/training/sales-reps'
    | '/api/public/v1/invoices/$id'
    | '/api/public/v1/pay/$invoiceId'
    | '/api/public/v1/terminals/heartbeat'
    | '/api/public/v1/terminals/invoice'
    | '/api/public/v1/terminals/options'
    | '/api/public/v1/terminals/pair'
    | '/api/public/v1/terminals/invoice/$id'
    | '/api/public/v1/terminals/invoice/$id/cancel'
    | '/api/public/v1/terminals/invoice/$id/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brand'
    | '/cash-out'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/docs'
    | '/integrate'
    | '/investors'
    | '/live'
    | '/m'
    | '/manifesto'
    | '/onramp'
    | '/pos-apk'
    | '/pos-build-id'
    | '/price'
    | '/pricing'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/where'
    | '/billing'
    | '/dashboard'
    | '/exports'
    | '/notifications'
    | '/terminals'
    | '/checkout/thanks'
    | '/dev/tangem-test'
    | '/docs/tap-to-pay-tangem'
    | '/docs/wallet-setup'
    | '/i/$invoiceId'
    | '/integrations/woocommerce'
    | '/pay/$invoiceId'
    | '/pos/history'
    | '/pos/nfc-inspect'
    | '/pos/pair'
    | '/pos/pair-signin'
    | '/pos/printer-test'
    | '/pos/settings'
    | '/sdk/payhme.js'
    | '/integrations'
    | '/pos'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/merchants'
    | '/m/home'
    | '/m/virtual-terminal'
    | '/stores/new'
    | '/admin'
    | '/stores'
    | '/admin/knowledge/convenience-doctrine'
    | '/admin/knowledge/executive-summary'
    | '/admin/knowledge/manifesto'
    | '/admin/knowledge/members-heatmap'
    | '/admin/knowledge/privacy'
    | '/admin/knowledge/terms'
    | '/stores/$storeId/chains'
    | '/stores/$storeId/keys'
    | '/stores/$storeId/kyc'
    | '/stores/$storeId/listing'
    | '/stores/$storeId/pos-settings'
    | '/stores/$storeId/tangem'
    | '/stores/$storeId/terminals'
    | '/api/public/auth/wallet-callback'
    | '/api/public/auth/wallet-challenge'
    | '/api/public/auth/wallet-exchange'
    | '/api/public/auth/wallet-status'
    | '/api/public/cron/alchemy-sync'
    | '/api/public/cron/billing'
    | '/api/public/cron/rates'
    | '/api/public/cron/watcher'
    | '/api/public/hooks/alchemy-activity'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/invoices'
    | '/api/public/v1/me'
    | '/api/public/v1/wallet-link'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/knowledge'
    | '/stores/$storeId'
    | '/admin/knowledge/pitch/consumers'
    | '/admin/knowledge/pitch/merchants'
    | '/admin/knowledge/pitch/new-markets'
    | '/admin/knowledge/training/cryptopop'
    | '/admin/knowledge/training/merchant-onboarding'
    | '/admin/knowledge/training/sales-reps'
    | '/api/public/v1/invoices/$id'
    | '/api/public/v1/pay/$invoiceId'
    | '/api/public/v1/terminals/heartbeat'
    | '/api/public/v1/terminals/invoice'
    | '/api/public/v1/terminals/options'
    | '/api/public/v1/terminals/pair'
    | '/api/public/v1/terminals/invoice/$id'
    | '/api/public/v1/terminals/invoice/$id/cancel'
    | '/api/public/v1/terminals/invoice/$id/receipt'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/brand'
    | '/cash-out'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/docs'
    | '/integrate'
    | '/investors'
    | '/live'
    | '/m'
    | '/manifesto'
    | '/onramp'
    | '/pos'
    | '/pos-apk'
    | '/pos-build-id'
    | '/price'
    | '/pricing'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/where'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/exports'
    | '/_authenticated/notifications'
    | '/_authenticated/terminals'
    | '/checkout/thanks'
    | '/dev/tangem-test'
    | '/docs/tap-to-pay-tangem'
    | '/docs/wallet-setup'
    | '/i/$invoiceId'
    | '/integrations/woocommerce'
    | '/pay/$invoiceId'
    | '/pos/history'
    | '/pos/nfc-inspect'
    | '/pos/pair'
    | '/pos/pair-signin'
    | '/pos/printer-test'
    | '/pos/settings'
    | '/sdk/payhme.js'
    | '/integrations/'
    | '/pos/'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/merchants'
    | '/_authenticated/m/home'
    | '/_authenticated/m/virtual-terminal'
    | '/_authenticated/stores/$storeId'
    | '/_authenticated/stores/new'
    | '/_authenticated/admin/'
    | '/_authenticated/stores/'
    | '/_authenticated/admin/knowledge/convenience-doctrine'
    | '/_authenticated/admin/knowledge/executive-summary'
    | '/_authenticated/admin/knowledge/manifesto'
    | '/_authenticated/admin/knowledge/members-heatmap'
    | '/_authenticated/admin/knowledge/privacy'
    | '/_authenticated/admin/knowledge/terms'
    | '/_authenticated/stores/$storeId/chains'
    | '/_authenticated/stores/$storeId/keys'
    | '/_authenticated/stores/$storeId/kyc'
    | '/_authenticated/stores/$storeId/listing'
    | '/_authenticated/stores/$storeId/pos-settings'
    | '/_authenticated/stores/$storeId/tangem'
    | '/_authenticated/stores/$storeId/terminals'
    | '/api/public/auth/wallet-callback'
    | '/api/public/auth/wallet-challenge'
    | '/api/public/auth/wallet-exchange'
    | '/api/public/auth/wallet-status'
    | '/api/public/cron/alchemy-sync'
    | '/api/public/cron/billing'
    | '/api/public/cron/rates'
    | '/api/public/cron/watcher'
    | '/api/public/hooks/alchemy-activity'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/invoices'
    | '/api/public/v1/me'
    | '/api/public/v1/wallet-link'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/knowledge/'
    | '/_authenticated/stores/$storeId/'
    | '/_authenticated/admin/knowledge/pitch/consumers'
    | '/_authenticated/admin/knowledge/pitch/merchants'
    | '/_authenticated/admin/knowledge/pitch/new-markets'
    | '/_authenticated/admin/knowledge/training/cryptopop'
    | '/_authenticated/admin/knowledge/training/merchant-onboarding'
    | '/_authenticated/admin/knowledge/training/sales-reps'
    | '/api/public/v1/invoices/$id'
    | '/api/public/v1/pay/$invoiceId'
    | '/api/public/v1/terminals/heartbeat'
    | '/api/public/v1/terminals/invoice'
    | '/api/public/v1/terminals/options'
    | '/api/public/v1/terminals/pair'
    | '/api/public/v1/terminals/invoice/$id'
    | '/api/public/v1/terminals/invoice/$id/cancel'
    | '/api/public/v1/terminals/invoice/$id/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrandRoute: typeof BrandRoute
  CashOutRoute: typeof CashOutRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  IntegrateRoute: typeof IntegrateRoute
  InvestorsRoute: typeof InvestorsRoute
  LiveRoute: typeof LiveRoute
  MRoute: typeof MRoute
  ManifestoRoute: typeof ManifestoRoute
  OnrampRoute: typeof OnrampRoute
  PosRoute: typeof PosRouteWithChildren
  PosApkRoute: typeof PosApkRoute
  PosBuildIdRoute: typeof PosBuildIdRoute
  PriceRoute: typeof PriceRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  WhereRoute: typeof WhereRoute
  DevTangemTestRoute: typeof DevTangemTestRoute
  IInvoiceIdRoute: typeof IInvoiceIdRoute
  IntegrationsWoocommerceRoute: typeof IntegrationsWoocommerceRoute
  PayInvoiceIdRoute: typeof PayInvoiceIdRoute
  SdkPayhmeDotjsRoute: typeof SdkPayhmeDotjsRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  ApiPublicAuthWalletCallbackRoute: typeof ApiPublicAuthWalletCallbackRoute
  ApiPublicAuthWalletChallengeRoute: typeof ApiPublicAuthWalletChallengeRoute
  ApiPublicAuthWalletExchangeRoute: typeof ApiPublicAuthWalletExchangeRoute
  ApiPublicAuthWalletStatusRoute: typeof ApiPublicAuthWalletStatusRoute
  ApiPublicCronAlchemySyncRoute: typeof ApiPublicCronAlchemySyncRoute
  ApiPublicCronBillingRoute: typeof ApiPublicCronBillingRoute
  ApiPublicCronRatesRoute: typeof ApiPublicCronRatesRoute
  ApiPublicCronWatcherRoute: typeof ApiPublicCronWatcherRoute
  ApiPublicHooksAlchemyActivityRoute: typeof ApiPublicHooksAlchemyActivityRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicV1InvoicesRoute: typeof ApiPublicV1InvoicesRouteWithChildren
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
  ApiPublicV1WalletLinkRoute: typeof ApiPublicV1WalletLinkRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicV1PayInvoiceIdRoute: typeof ApiPublicV1PayInvoiceIdRoute
  ApiPublicV1TerminalsHeartbeatRoute: typeof ApiPublicV1TerminalsHeartbeatRoute
  ApiPublicV1TerminalsInvoiceRoute: typeof ApiPublicV1TerminalsInvoiceRouteWithChildren
  ApiPublicV1TerminalsOptionsRoute: typeof ApiPublicV1TerminalsOptionsRoute
  ApiPublicV1TerminalsPairRoute: typeof ApiPublicV1TerminalsPairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/where': {
      id: '/where'
      path: '/where'
      fullPath: '/where'
      preLoaderRoute: typeof WhereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price': {
      id: '/price'
      path: '/price'
      fullPath: '/price'
      preLoaderRoute: typeof PriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-build-id': {
      id: '/pos-build-id'
      path: '/pos-build-id'
      fullPath: '/pos-build-id'
      preLoaderRoute: typeof PosBuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-apk': {
      id: '/pos-apk'
      path: '/pos-apk'
      fullPath: '/pos-apk'
      preLoaderRoute: typeof PosApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onramp': {
      id: '/onramp'
      path: '/onramp'
      fullPath: '/onramp'
      preLoaderRoute: typeof OnrampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrate': {
      id: '/integrate'
      path: '/integrate'
      fullPath: '/integrate'
      preLoaderRoute: typeof IntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-out': {
      id: '/cash-out'
      path: '/cash-out'
      fullPath: '/cash-out'
      preLoaderRoute: typeof CashOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk/payhme.js': {
      id: '/sdk/payhme.js'
      path: '/sdk/payhme.js'
      fullPath: '/sdk/payhme.js'
      preLoaderRoute: typeof SdkPayhmeDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/settings': {
      id: '/pos/settings'
      path: '/settings'
      fullPath: '/pos/settings'
      preLoaderRoute: typeof PosSettingsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/printer-test': {
      id: '/pos/printer-test'
      path: '/printer-test'
      fullPath: '/pos/printer-test'
      preLoaderRoute: typeof PosPrinterTestRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/pair-signin': {
      id: '/pos/pair-signin'
      path: '/pair-signin'
      fullPath: '/pos/pair-signin'
      preLoaderRoute: typeof PosPairSigninRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/pair': {
      id: '/pos/pair'
      path: '/pair'
      fullPath: '/pos/pair'
      preLoaderRoute: typeof PosPairRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/nfc-inspect': {
      id: '/pos/nfc-inspect'
      path: '/nfc-inspect'
      fullPath: '/pos/nfc-inspect'
      preLoaderRoute: typeof PosNfcInspectRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/history': {
      id: '/pos/history'
      path: '/history'
      fullPath: '/pos/history'
      preLoaderRoute: typeof PosHistoryRouteImport
      parentRoute: typeof PosRoute
    }
    '/pay/$invoiceId': {
      id: '/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/woocommerce': {
      id: '/integrations/woocommerce'
      path: '/integrations/woocommerce'
      fullPath: '/integrations/woocommerce'
      preLoaderRoute: typeof IntegrationsWoocommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$invoiceId': {
      id: '/i/$invoiceId'
      path: '/i/$invoiceId'
      fullPath: '/i/$invoiceId'
      preLoaderRoute: typeof IInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/wallet-setup': {
      id: '/docs/wallet-setup'
      path: '/wallet-setup'
      fullPath: '/docs/wallet-setup'
      preLoaderRoute: typeof DocsWalletSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tap-to-pay-tangem': {
      id: '/docs/tap-to-pay-tangem'
      path: '/tap-to-pay-tangem'
      fullPath: '/docs/tap-to-pay-tangem'
      preLoaderRoute: typeof DocsTapToPayTangemRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dev/tangem-test': {
      id: '/dev/tangem-test'
      path: '/dev/tangem-test'
      fullPath: '/dev/tangem-test'
      preLoaderRoute: typeof DevTangemTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/thanks': {
      id: '/checkout/thanks'
      path: '/thanks'
      fullPath: '/checkout/thanks'
      preLoaderRoute: typeof CheckoutThanksRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/terminals': {
      id: '/_authenticated/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof AuthenticatedTerminalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exports': {
      id: '/_authenticated/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stores/': {
      id: '/_authenticated/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof AuthenticatedStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/stores/new': {
      id: '/_authenticated/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof AuthenticatedStoresNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stores/$storeId': {
      id: '/_authenticated/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/m/virtual-terminal': {
      id: '/_authenticated/m/virtual-terminal'
      path: '/m/virtual-terminal'
      fullPath: '/m/virtual-terminal'
      preLoaderRoute: typeof AuthenticatedMVirtualTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/m/home': {
      id: '/_authenticated/m/home'
      path: '/m/home'
      fullPath: '/m/home'
      preLoaderRoute: typeof AuthenticatedMHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/merchants': {
      id: '/_authenticated/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AuthenticatedAdminMerchantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/stores/$storeId/': {
      id: '/_authenticated/stores/$storeId/'
      path: '/'
      fullPath: '/stores/$storeId/'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdIndexRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/admin/knowledge/': {
      id: '/_authenticated/admin/knowledge/'
      path: '/'
      fullPath: '/admin/knowledge/'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/wallet-link': {
      id: '/api/public/v1/wallet-link'
      path: '/api/public/v1/wallet-link'
      fullPath: '/api/public/v1/wallet-link'
      preLoaderRoute: typeof ApiPublicV1WalletLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/invoices': {
      id: '/api/public/v1/invoices'
      path: '/api/public/v1/invoices'
      fullPath: '/api/public/v1/invoices'
      preLoaderRoute: typeof ApiPublicV1InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/alchemy-activity': {
      id: '/api/public/hooks/alchemy-activity'
      path: '/api/public/hooks/alchemy-activity'
      fullPath: '/api/public/hooks/alchemy-activity'
      preLoaderRoute: typeof ApiPublicHooksAlchemyActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/watcher': {
      id: '/api/public/cron/watcher'
      path: '/api/public/cron/watcher'
      fullPath: '/api/public/cron/watcher'
      preLoaderRoute: typeof ApiPublicCronWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/rates': {
      id: '/api/public/cron/rates'
      path: '/api/public/cron/rates'
      fullPath: '/api/public/cron/rates'
      preLoaderRoute: typeof ApiPublicCronRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/billing': {
      id: '/api/public/cron/billing'
      path: '/api/public/cron/billing'
      fullPath: '/api/public/cron/billing'
      preLoaderRoute: typeof ApiPublicCronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/alchemy-sync': {
      id: '/api/public/cron/alchemy-sync'
      path: '/api/public/cron/alchemy-sync'
      fullPath: '/api/public/cron/alchemy-sync'
      preLoaderRoute: typeof ApiPublicCronAlchemySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-status': {
      id: '/api/public/auth/wallet-status'
      path: '/api/public/auth/wallet-status'
      fullPath: '/api/public/auth/wallet-status'
      preLoaderRoute: typeof ApiPublicAuthWalletStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-exchange': {
      id: '/api/public/auth/wallet-exchange'
      path: '/api/public/auth/wallet-exchange'
      fullPath: '/api/public/auth/wallet-exchange'
      preLoaderRoute: typeof ApiPublicAuthWalletExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-challenge': {
      id: '/api/public/auth/wallet-challenge'
      path: '/api/public/auth/wallet-challenge'
      fullPath: '/api/public/auth/wallet-challenge'
      preLoaderRoute: typeof ApiPublicAuthWalletChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-callback': {
      id: '/api/public/auth/wallet-callback'
      path: '/api/public/auth/wallet-callback'
      fullPath: '/api/public/auth/wallet-callback'
      preLoaderRoute: typeof ApiPublicAuthWalletCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stores/$storeId/terminals': {
      id: '/_authenticated/stores/$storeId/terminals'
      path: '/terminals'
      fullPath: '/stores/$storeId/terminals'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdTerminalsRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/tangem': {
      id: '/_authenticated/stores/$storeId/tangem'
      path: '/tangem'
      fullPath: '/stores/$storeId/tangem'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdTangemRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/pos-settings': {
      id: '/_authenticated/stores/$storeId/pos-settings'
      path: '/pos-settings'
      fullPath: '/stores/$storeId/pos-settings'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdPosSettingsRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/listing': {
      id: '/_authenticated/stores/$storeId/listing'
      path: '/listing'
      fullPath: '/stores/$storeId/listing'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdListingRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/kyc': {
      id: '/_authenticated/stores/$storeId/kyc'
      path: '/kyc'
      fullPath: '/stores/$storeId/kyc'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdKycRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/keys': {
      id: '/_authenticated/stores/$storeId/keys'
      path: '/keys'
      fullPath: '/stores/$storeId/keys'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdKeysRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/chains': {
      id: '/_authenticated/stores/$storeId/chains'
      path: '/chains'
      fullPath: '/stores/$storeId/chains'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdChainsRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/admin/knowledge/terms': {
      id: '/_authenticated/admin/knowledge/terms'
      path: '/terms'
      fullPath: '/admin/knowledge/terms'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTermsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/privacy': {
      id: '/_authenticated/admin/knowledge/privacy'
      path: '/privacy'
      fullPath: '/admin/knowledge/privacy'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePrivacyRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/members-heatmap': {
      id: '/_authenticated/admin/knowledge/members-heatmap'
      path: '/members-heatmap'
      fullPath: '/admin/knowledge/members-heatmap'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeMembersHeatmapRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/manifesto': {
      id: '/_authenticated/admin/knowledge/manifesto'
      path: '/manifesto'
      fullPath: '/admin/knowledge/manifesto'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeManifestoRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/executive-summary': {
      id: '/_authenticated/admin/knowledge/executive-summary'
      path: '/executive-summary'
      fullPath: '/admin/knowledge/executive-summary'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeExecutiveSummaryRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/convenience-doctrine': {
      id: '/_authenticated/admin/knowledge/convenience-doctrine'
      path: '/convenience-doctrine'
      fullPath: '/admin/knowledge/convenience-doctrine'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/api/public/v1/terminals/pair': {
      id: '/api/public/v1/terminals/pair'
      path: '/api/public/v1/terminals/pair'
      fullPath: '/api/public/v1/terminals/pair'
      preLoaderRoute: typeof ApiPublicV1TerminalsPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/terminals/options': {
      id: '/api/public/v1/terminals/options'
      path: '/api/public/v1/terminals/options'
      fullPath: '/api/public/v1/terminals/options'
      preLoaderRoute: typeof ApiPublicV1TerminalsOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/terminals/invoice': {
      id: '/api/public/v1/terminals/invoice'
      path: '/api/public/v1/terminals/invoice'
      fullPath: '/api/public/v1/terminals/invoice'
      preLoaderRoute: typeof ApiPublicV1TerminalsInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/terminals/heartbeat': {
      id: '/api/public/v1/terminals/heartbeat'
      path: '/api/public/v1/terminals/heartbeat'
      fullPath: '/api/public/v1/terminals/heartbeat'
      preLoaderRoute: typeof ApiPublicV1TerminalsHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/pay/$invoiceId': {
      id: '/api/public/v1/pay/$invoiceId'
      path: '/api/public/v1/pay/$invoiceId'
      fullPath: '/api/public/v1/pay/$invoiceId'
      preLoaderRoute: typeof ApiPublicV1PayInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/invoices/$id': {
      id: '/api/public/v1/invoices/$id'
      path: '/$id'
      fullPath: '/api/public/v1/invoices/$id'
      preLoaderRoute: typeof ApiPublicV1InvoicesIdRouteImport
      parentRoute: typeof ApiPublicV1InvoicesRoute
    }
    '/_authenticated/admin/knowledge/training/sales-reps': {
      id: '/_authenticated/admin/knowledge/training/sales-reps'
      path: '/training/sales-reps'
      fullPath: '/admin/knowledge/training/sales-reps'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/training/merchant-onboarding': {
      id: '/_authenticated/admin/knowledge/training/merchant-onboarding'
      path: '/training/merchant-onboarding'
      fullPath: '/admin/knowledge/training/merchant-onboarding'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/training/cryptopop': {
      id: '/_authenticated/admin/knowledge/training/cryptopop'
      path: '/training/cryptopop'
      fullPath: '/admin/knowledge/training/cryptopop'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTrainingCryptopopRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/pitch/new-markets': {
      id: '/_authenticated/admin/knowledge/pitch/new-markets'
      path: '/pitch/new-markets'
      fullPath: '/admin/knowledge/pitch/new-markets'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePitchNewMarketsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/pitch/merchants': {
      id: '/_authenticated/admin/knowledge/pitch/merchants'
      path: '/pitch/merchants'
      fullPath: '/admin/knowledge/pitch/merchants'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePitchMerchantsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/pitch/consumers': {
      id: '/_authenticated/admin/knowledge/pitch/consumers'
      path: '/pitch/consumers'
      fullPath: '/admin/knowledge/pitch/consumers'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePitchConsumersRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/api/public/v1/terminals/invoice/$id': {
      id: '/api/public/v1/terminals/invoice/$id'
      path: '/$id'
      fullPath: '/api/public/v1/terminals/invoice/$id'
      preLoaderRoute: typeof ApiPublicV1TerminalsInvoiceIdRouteImport
      parentRoute: typeof ApiPublicV1TerminalsInvoiceRoute
    }
    '/api/public/v1/terminals/invoice/$id/receipt': {
      id: '/api/public/v1/terminals/invoice/$id/receipt'
      path: '/receipt'
      fullPath: '/api/public/v1/terminals/invoice/$id/receipt'
      preLoaderRoute: typeof ApiPublicV1TerminalsInvoiceIdReceiptRouteImport
      parentRoute: typeof ApiPublicV1TerminalsInvoiceIdRoute
    }
    '/api/public/v1/terminals/invoice/$id/cancel': {
      id: '/api/public/v1/terminals/invoice/$id/cancel'
      path: '/cancel'
      fullPath: '/api/public/v1/terminals/invoice/$id/cancel'
      preLoaderRoute: typeof ApiPublicV1TerminalsInvoiceIdCancelRouteImport
      parentRoute: typeof ApiPublicV1TerminalsInvoiceIdRoute
    }
  }
}

interface AuthenticatedAdminKnowledgeRouteChildren {
  AuthenticatedAdminKnowledgeConvenienceDoctrineRoute: typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  AuthenticatedAdminKnowledgeExecutiveSummaryRoute: typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  AuthenticatedAdminKnowledgeManifestoRoute: typeof AuthenticatedAdminKnowledgeManifestoRoute
  AuthenticatedAdminKnowledgeMembersHeatmapRoute: typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  AuthenticatedAdminKnowledgePrivacyRoute: typeof AuthenticatedAdminKnowledgePrivacyRoute
  AuthenticatedAdminKnowledgeTermsRoute: typeof AuthenticatedAdminKnowledgeTermsRoute
  AuthenticatedAdminKnowledgeIndexRoute: typeof AuthenticatedAdminKnowledgeIndexRoute
  AuthenticatedAdminKnowledgePitchConsumersRoute: typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  AuthenticatedAdminKnowledgePitchMerchantsRoute: typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  AuthenticatedAdminKnowledgePitchNewMarketsRoute: typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  AuthenticatedAdminKnowledgeTrainingCryptopopRoute: typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute: typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  AuthenticatedAdminKnowledgeTrainingSalesRepsRoute: typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
}

const AuthenticatedAdminKnowledgeRouteChildren: AuthenticatedAdminKnowledgeRouteChildren =
  {
    AuthenticatedAdminKnowledgeConvenienceDoctrineRoute:
      AuthenticatedAdminKnowledgeConvenienceDoctrineRoute,
    AuthenticatedAdminKnowledgeExecutiveSummaryRoute:
      AuthenticatedAdminKnowledgeExecutiveSummaryRoute,
    AuthenticatedAdminKnowledgeManifestoRoute:
      AuthenticatedAdminKnowledgeManifestoRoute,
    AuthenticatedAdminKnowledgeMembersHeatmapRoute:
      AuthenticatedAdminKnowledgeMembersHeatmapRoute,
    AuthenticatedAdminKnowledgePrivacyRoute:
      AuthenticatedAdminKnowledgePrivacyRoute,
    AuthenticatedAdminKnowledgeTermsRoute:
      AuthenticatedAdminKnowledgeTermsRoute,
    AuthenticatedAdminKnowledgeIndexRoute:
      AuthenticatedAdminKnowledgeIndexRoute,
    AuthenticatedAdminKnowledgePitchConsumersRoute:
      AuthenticatedAdminKnowledgePitchConsumersRoute,
    AuthenticatedAdminKnowledgePitchMerchantsRoute:
      AuthenticatedAdminKnowledgePitchMerchantsRoute,
    AuthenticatedAdminKnowledgePitchNewMarketsRoute:
      AuthenticatedAdminKnowledgePitchNewMarketsRoute,
    AuthenticatedAdminKnowledgeTrainingCryptopopRoute:
      AuthenticatedAdminKnowledgeTrainingCryptopopRoute,
    AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute:
      AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute,
    AuthenticatedAdminKnowledgeTrainingSalesRepsRoute:
      AuthenticatedAdminKnowledgeTrainingSalesRepsRoute,
  }

const AuthenticatedAdminKnowledgeRouteWithChildren =
  AuthenticatedAdminKnowledgeRoute._addFileChildren(
    AuthenticatedAdminKnowledgeRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRouteWithChildren
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMerchantsRoute: typeof AuthenticatedAdminMerchantsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminKnowledgeRoute:
    AuthenticatedAdminKnowledgeRouteWithChildren,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMerchantsRoute: AuthenticatedAdminMerchantsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStoresStoreIdRouteChildren {
  AuthenticatedStoresStoreIdChainsRoute: typeof AuthenticatedStoresStoreIdChainsRoute
  AuthenticatedStoresStoreIdKeysRoute: typeof AuthenticatedStoresStoreIdKeysRoute
  AuthenticatedStoresStoreIdKycRoute: typeof AuthenticatedStoresStoreIdKycRoute
  AuthenticatedStoresStoreIdListingRoute: typeof AuthenticatedStoresStoreIdListingRoute
  AuthenticatedStoresStoreIdPosSettingsRoute: typeof AuthenticatedStoresStoreIdPosSettingsRoute
  AuthenticatedStoresStoreIdTangemRoute: typeof AuthenticatedStoresStoreIdTangemRoute
  AuthenticatedStoresStoreIdTerminalsRoute: typeof AuthenticatedStoresStoreIdTerminalsRoute
  AuthenticatedStoresStoreIdIndexRoute: typeof AuthenticatedStoresStoreIdIndexRoute
}

const AuthenticatedStoresStoreIdRouteChildren: AuthenticatedStoresStoreIdRouteChildren =
  {
    AuthenticatedStoresStoreIdChainsRoute:
      AuthenticatedStoresStoreIdChainsRoute,
    AuthenticatedStoresStoreIdKeysRoute: AuthenticatedStoresStoreIdKeysRoute,
    AuthenticatedStoresStoreIdKycRoute: AuthenticatedStoresStoreIdKycRoute,
    AuthenticatedStoresStoreIdListingRoute:
      AuthenticatedStoresStoreIdListingRoute,
    AuthenticatedStoresStoreIdPosSettingsRoute:
      AuthenticatedStoresStoreIdPosSettingsRoute,
    AuthenticatedStoresStoreIdTangemRoute:
      AuthenticatedStoresStoreIdTangemRoute,
    AuthenticatedStoresStoreIdTerminalsRoute:
      AuthenticatedStoresStoreIdTerminalsRoute,
    AuthenticatedStoresStoreIdIndexRoute: AuthenticatedStoresStoreIdIndexRoute,
  }

const AuthenticatedStoresStoreIdRouteWithChildren =
  AuthenticatedStoresStoreIdRoute._addFileChildren(
    AuthenticatedStoresStoreIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedTerminalsRoute: typeof AuthenticatedTerminalsRoute
  AuthenticatedMHomeRoute: typeof AuthenticatedMHomeRoute
  AuthenticatedMVirtualTerminalRoute: typeof AuthenticatedMVirtualTerminalRoute
  AuthenticatedStoresStoreIdRoute: typeof AuthenticatedStoresStoreIdRouteWithChildren
  AuthenticatedStoresNewRoute: typeof AuthenticatedStoresNewRoute
  AuthenticatedStoresIndexRoute: typeof AuthenticatedStoresIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedTerminalsRoute: AuthenticatedTerminalsRoute,
  AuthenticatedMHomeRoute: AuthenticatedMHomeRoute,
  AuthenticatedMVirtualTerminalRoute: AuthenticatedMVirtualTerminalRoute,
  AuthenticatedStoresStoreIdRoute: AuthenticatedStoresStoreIdRouteWithChildren,
  AuthenticatedStoresNewRoute: AuthenticatedStoresNewRoute,
  AuthenticatedStoresIndexRoute: AuthenticatedStoresIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutThanksRoute: typeof CheckoutThanksRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutThanksRoute: CheckoutThanksRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface DocsRouteChildren {
  DocsTapToPayTangemRoute: typeof DocsTapToPayTangemRoute
  DocsWalletSetupRoute: typeof DocsWalletSetupRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTapToPayTangemRoute: DocsTapToPayTangemRoute,
  DocsWalletSetupRoute: DocsWalletSetupRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface PosRouteChildren {
  PosHistoryRoute: typeof PosHistoryRoute
  PosNfcInspectRoute: typeof PosNfcInspectRoute
  PosPairRoute: typeof PosPairRoute
  PosPairSigninRoute: typeof PosPairSigninRoute
  PosPrinterTestRoute: typeof PosPrinterTestRoute
  PosSettingsRoute: typeof PosSettingsRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosHistoryRoute: PosHistoryRoute,
  PosNfcInspectRoute: PosNfcInspectRoute,
  PosPairRoute: PosPairRoute,
  PosPairSigninRoute: PosPairSigninRoute,
  PosPrinterTestRoute: PosPrinterTestRoute,
  PosSettingsRoute: PosSettingsRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface ApiPublicV1InvoicesRouteChildren {
  ApiPublicV1InvoicesIdRoute: typeof ApiPublicV1InvoicesIdRoute
}

const ApiPublicV1InvoicesRouteChildren: ApiPublicV1InvoicesRouteChildren = {
  ApiPublicV1InvoicesIdRoute: ApiPublicV1InvoicesIdRoute,
}

const ApiPublicV1InvoicesRouteWithChildren =
  ApiPublicV1InvoicesRoute._addFileChildren(ApiPublicV1InvoicesRouteChildren)

interface ApiPublicV1TerminalsInvoiceIdRouteChildren {
  ApiPublicV1TerminalsInvoiceIdCancelRoute: typeof ApiPublicV1TerminalsInvoiceIdCancelRoute
  ApiPublicV1TerminalsInvoiceIdReceiptRoute: typeof ApiPublicV1TerminalsInvoiceIdReceiptRoute
}

const ApiPublicV1TerminalsInvoiceIdRouteChildren: ApiPublicV1TerminalsInvoiceIdRouteChildren =
  {
    ApiPublicV1TerminalsInvoiceIdCancelRoute:
      ApiPublicV1TerminalsInvoiceIdCancelRoute,
    ApiPublicV1TerminalsInvoiceIdReceiptRoute:
      ApiPublicV1TerminalsInvoiceIdReceiptRoute,
  }

const ApiPublicV1TerminalsInvoiceIdRouteWithChildren =
  ApiPublicV1TerminalsInvoiceIdRoute._addFileChildren(
    ApiPublicV1TerminalsInvoiceIdRouteChildren,
  )

interface ApiPublicV1TerminalsInvoiceRouteChildren {
  ApiPublicV1TerminalsInvoiceIdRoute: typeof ApiPublicV1TerminalsInvoiceIdRouteWithChildren
}

const ApiPublicV1TerminalsInvoiceRouteChildren: ApiPublicV1TerminalsInvoiceRouteChildren =
  {
    ApiPublicV1TerminalsInvoiceIdRoute:
      ApiPublicV1TerminalsInvoiceIdRouteWithChildren,
  }

const ApiPublicV1TerminalsInvoiceRouteWithChildren =
  ApiPublicV1TerminalsInvoiceRoute._addFileChildren(
    ApiPublicV1TerminalsInvoiceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BrandRoute: BrandRoute,
  CashOutRoute: CashOutRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  IntegrateRoute: IntegrateRoute,
  InvestorsRoute: InvestorsRoute,
  LiveRoute: LiveRoute,
  MRoute: MRoute,
  ManifestoRoute: ManifestoRoute,
  OnrampRoute: OnrampRoute,
  PosRoute: PosRouteWithChildren,
  PosApkRoute: PosApkRoute,
  PosBuildIdRoute: PosBuildIdRoute,
  PriceRoute: PriceRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  WhereRoute: WhereRoute,
  DevTangemTestRoute: DevTangemTestRoute,
  IInvoiceIdRoute: IInvoiceIdRoute,
  IntegrationsWoocommerceRoute: IntegrationsWoocommerceRoute,
  PayInvoiceIdRoute: PayInvoiceIdRoute,
  SdkPayhmeDotjsRoute: SdkPayhmeDotjsRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  ApiPublicAuthWalletCallbackRoute: ApiPublicAuthWalletCallbackRoute,
  ApiPublicAuthWalletChallengeRoute: ApiPublicAuthWalletChallengeRoute,
  ApiPublicAuthWalletExchangeRoute: ApiPublicAuthWalletExchangeRoute,
  ApiPublicAuthWalletStatusRoute: ApiPublicAuthWalletStatusRoute,
  ApiPublicCronAlchemySyncRoute: ApiPublicCronAlchemySyncRoute,
  ApiPublicCronBillingRoute: ApiPublicCronBillingRoute,
  ApiPublicCronRatesRoute: ApiPublicCronRatesRoute,
  ApiPublicCronWatcherRoute: ApiPublicCronWatcherRoute,
  ApiPublicHooksAlchemyActivityRoute: ApiPublicHooksAlchemyActivityRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicV1InvoicesRoute: ApiPublicV1InvoicesRouteWithChildren,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
  ApiPublicV1WalletLinkRoute: ApiPublicV1WalletLinkRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicV1PayInvoiceIdRoute: ApiPublicV1PayInvoiceIdRoute,
  ApiPublicV1TerminalsHeartbeatRoute: ApiPublicV1TerminalsHeartbeatRoute,
  ApiPublicV1TerminalsInvoiceRoute:
    ApiPublicV1TerminalsInvoiceRouteWithChildren,
  ApiPublicV1TerminalsOptionsRoute: ApiPublicV1TerminalsOptionsRoute,
  ApiPublicV1TerminalsPairRoute: ApiPublicV1TerminalsPairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
